(function(){
var LABELS={C:'변액종신',F:'변액유니버셜종신',E:'변액적립',D:'변액연금'},GROUP_ORDER={C:0,F:1,E:2,D:3},active='ALL',sortKey='default',sortDir='asc';
function e(id){return document.getElementById(id)}
function fmt(v){return v==null?'-':Number(v).toLocaleString('ko-KR',{minimumFractionDigits:2,maximumFractionDigits:2})}
function pct(v){return v==null?'-':Number(v).toFixed(2)+'%'}
function dayret(r){if(r[4]==null||r[5]==null)return null;var prev=Number(r[4])-Number(r[5]);return prev?Number(r[5])/prev*100:null}
function cumret(r){return r[4]==null?null:(Number(r[4])-1000)/1000*100}
function years(r){if(!r[3]||typeof DATA_META==='undefined')return null;var p=r[3].split('.'),d=DATA_META.date.split('.'),s=new Date(+p[0],+p[1]-1,+p[2]),t=new Date(+d[0],+d[1]-1,+d[2]);return (t-s)/(365.25*86400000)}
function annualret(r){var y=years(r),c=cumret(r);if(y==null||y<1||c==null)return null;return c/y}
function annualRanks(){var a=FUNDS.filter(function(r){return annualret(r)!=null}).slice().sort(function(a,b){return annualret(b)-annualret(a)}),m={};a.forEach(function(r,i){m[r[0]+'|'+r[1]]=i+1});return m}
function val(r,k){if(k==='rank')return annualRanks()[r[0]+'|'+r[1]]??null;if(k==='dayret')return dayret(r);if(k==='annual')return annualret(r);return r[{group:0,code:1,name:2,setting:3,nav:4,change:5,aum:7}[k]]}
function rows(){var q=(e('search').value||'').trim().toLowerCase(),a=FUNDS.filter(function(r){return(active==='ALL'||r[0]===active)&&(!q||r[1].toLowerCase().includes(q)||r[2].toLowerCase().includes(q))});a.sort(function(x,y){if(sortKey==='default'){var g=(GROUP_ORDER[x[0]]??99)-(GROUP_ORDER[y[0]]??99);if(g!==0)return g;return x[1].localeCompare(y[1])}var vx=val(x,sortKey),vy=val(y,sortKey);if(vx==null&&vy==null)return 0;if(vx==null)return 1;if(vy==null)return-1;var c=(typeof vx==='number'&&typeof vy==='number')?vx-vy:String(vx).localeCompare(String(vy),'ko');return sortDir==='asc'?c:-c});return a}
function render(){var a=rows(),ranks=annualRanks();e('barTitle').textContent=active==='ALL'?'전체 · C/F/E/D 펀드 Line-up':active+'군 · '+LABELS[active];e('count').textContent=a.length+'개';e('tbody').innerHTML=a.map(function(r){var dr=dayret(r),ar=annualret(r),rank=ranks[r[0]+'|'+r[1]]??null,cc=r[5]>0?'up':r[5]<0?'down':'',dc=dr>0?'up':dr<0?'down':'';return'<tr><td><span class="chip '+r[0]+'">'+r[0]+'군 · '+LABELS[r[0]]+'</span></td><td class="rank">'+(rank??'-')+'</td><td class="code">'+r[1]+'</td><td>'+r[2]+'</td><td>'+r[3]+'</td><td class="num">'+fmt(r[4])+'</td><td class="num '+cc+'">'+(r[5]==null?'-':(r[5]>0?'+':'')+fmt(r[5]))+'</td><td class="num">'+pct(ar)+'</td><td class="num '+dc+'">'+pct(dr)+'</td><td class="num">'+(r[7]==null?'-':fmt(r[7])+'억')+'</td></tr>'}).join('')}
function sortedAnnual(n){return FUNDS.filter(function(r){return annualret(r)!=null}).slice().sort(function(a,b){return annualret(b)-annualret(a)}).slice(0,n)}
function sortedDay(n,asc){return FUNDS.filter(function(r){return dayret(r)!=null}).slice().sort(function(a,b){return asc?dayret(a)-dayret(b):dayret(b)-dayret(a)}).slice(0,n)}
function lists(){e('top').innerHTML=sortedAnnual(10).map(function(r,i){return'<li><span>'+(i+1)+'</span><b>'+r[1]+'</b><span>'+r[2]+'</span><strong class="up">'+fmt(annualret(r))+'%</strong></li>'}).join('');e('up').innerHTML=sortedDay(5,false).map(function(r,i){return'<tr><td>'+(i+1)+'</td><td>'+r[1]+'</td><td>'+r[2]+'</td><td class="up">'+pct(dayret(r))+'</td></tr>').join('');e('down').innerHTML=sortedDay(5,true).map(function(r,i){return'<tr><td>'+(i+1)+'</td><td>'+r[1]+'</td><td>'+r[2]+'</td><td class="down">'+pct(dayret(r))+'</td></tr>').join('');var nav=FUNDS.filter(function(r){return r[4]!=null}).slice().sort(function(a,b){return b[4]-a[4]})[0],ann=sortedAnnual(1)[0],aum=FUNDS.filter(function(r){return r[7]!=null}).slice().sort(function(a,b){return b[7]-a[7]})[0],old=FUNDS.filter(function(r){return r[3]}).slice().sort(function(a,b){return String(a[3]).localeCompare(String(b[3]))})[0];e('topNav').innerHTML=nav?'<span><b>기준가 TOP</b> '+nav[1]+' '+nav[2]+'</span><strong>'+fmt(nav[4])+'</strong>':'-';e('topAnn').innerHTML=ann?'<span><b>연환산 TOP</b> '+ann[1]+' '+ann[2]+'</span><strong>'+fmt(annualret(ann))+'%</strong>':'-';e('topAum').innerHTML=aum?'<span><b>자산 TOP</b> '+aum[1]+' '+aum[2]+'</span><strong>'+fmt(aum[7])+'억</strong>':'-';e('topOld').innerHTML=old?'<span><b>가장 오래된 펀드</b> '+old[1]+' '+old[2]+'</span><strong>'+old[3]+'</strong>':'-'}
function syncMeta(){if(typeof DATA_META==='undefined')return;var sec=[].slice.call(document.querySelectorAll('section.sec')).find(function(s){var h=s.querySelector('h2.title');return h&&h.textContent.indexOf('교보생명 변액보험')>=0});if(sec){var card=sec.querySelector('.card');if(card){card.innerHTML='<b>공식 기준가 확인 안내</b><br><span class="muted"><b>'+DATA_META.date+'</b> 기준 교보생명 변액보험 <b>'+DATA_META.verified+'개 / '+DATA_META.total+'개</b> 펀드의 기준가·전일대비·순자산을 반영했습니다. 누적수익률과 연환산수익률은 FPON 계산식으로 자동 산출합니다.</span>'}var tabs=sec.querySelector('.tabs');if(tabs){['ALL','C','F','E','D'].forEach(function(g){var b=tabs.querySelector('[data-g="'+g+'"]');if(b)tabs.appendChild(b)})}}var footer=document.querySelector('footer');if(footer)footer.innerHTML='※ 교보생명 변액보험 데이터는 <b>'+DATA_META.date+'</b> 기준입니다. '+DATA_META.verified+'/'+DATA_META.total+'개 펀드 반영 완료.<br>※ 누적수익률=(기준가-1,000)÷1,000×100, 연환산수익률=누적수익률÷운용기간(년). 설정 1년 미만 펀드는 연환산 순위에서 제외합니다.'}
document.querySelectorAll('.tab').forEach(function(b){b.onclick=function(){document.querySelectorAll('.tab').forEach(function(x){x.classList.remove('on')});b.classList.add('on');active=b.dataset.g;sortKey='default';sortDir='asc';render()}});
document.querySelectorAll('.sortable').forEach(function(th){th.onclick=function(){var k=th.dataset.k;if(sortKey===k)sortDir=sortDir==='asc'?'desc':'asc';else{sortKey=k;sortDir='asc'}render()}});
e('search').oninput=render;
window.copySummary=function(){var a=sortedAnnual(1)[0],b=sortedDay(1,false)[0],c=sortedDay(1,true)[0];navigator.clipboard.writeText('FPON TODAY IS... | 2026.08.27\n교보생명 변액보험 기준가: '+DATA_META.date+' 공식 공시 78개 전체 기준\n연환산 TOP: '+(a?a[1]+' '+a[2]+' '+fmt(annualret(a))+'%':'-')+'\n전일 상승 TOP: '+(b?b[1]+' '+pct(dayret(b)):'-')+'\n전일 하락 TOP: '+(c?c[1]+' '+pct(dayret(c)):'-')).then(function(){alert('오늘 요약을 복사했습니다.')})};
if(typeof FUNDS==='undefined'){e('tbody').innerHTML='<tr><td colspan="10" class="loading">변액보험 데이터 로딩 실패</td></tr>';return}
syncMeta();render();lists();
})();