(function(){
const FORTUNES={
rat:{name:'쥐띠',icon:'🐭',summary:'우선순위를 정하면 흐름이 좋아집니다.',money:'충동지출보다 계획한 소비가 유리합니다.',work:'미뤄둔 연락과 확인 업무를 먼저 처리해보세요.',life:'짧게라도 휴식 시간을 확보하면 집중력이 좋아집니다.'},
ox:{name:'소띠',icon:'🐮',summary:'꾸준함이 결과를 만드는 날입니다.',money:'큰 변화보다 현재 계획을 지키는 편이 좋습니다.',work:'한 번 정한 순서를 끝까지 유지해보세요.',life:'무리한 일정 대신 생활 리듬을 지키는 것이 좋습니다.'},
tiger:{name:'호랑이띠',icon:'🐯',summary:'결정 전에 조건을 한 번 더 확인하세요.',money:'새로운 지출이나 투자는 비교 후 판단하세요.',work:'속도보다 정확한 확인이 좋은 결과로 이어집니다.',life:'감정적으로 반응하기보다 한 템포 여유를 가져보세요.'},
rabbit:{name:'토끼띠',icon:'🐰',summary:'대화 속에서 좋은 실마리를 찾을 수 있습니다.',money:'가족과의 재무 대화가 도움이 될 수 있습니다.',work:'혼자 판단하기보다 의견을 나누어보세요.',life:'가까운 사람과 편안한 대화가 기분 전환에 좋습니다.'},
dragon:{name:'용띠',icon:'🐲',summary:'미뤄둔 일을 시작하기 좋은 날입니다.',money:'정리하지 못한 자동이체나 고정비를 점검해보세요.',work:'첫 단계만 시작해도 일이 빠르게 풀릴 수 있습니다.',life:'새로운 루틴을 만들기 좋습니다.'},
snake:{name:'뱀띠',icon:'🐍',summary:'금전 판단은 조금 보수적으로 접근하세요.',money:'확실하지 않은 소비나 투자는 미루는 편이 좋습니다.',work:'자료와 숫자를 다시 확인하면 실수를 줄일 수 있습니다.',life:'과로보다 컨디션 관리에 신경 써보세요.'},
horse:{name:'말띠',icon:'🐴',summary:'움직일수록 기회가 보이는 날입니다.',money:'필요한 정보는 직접 찾아보는 것이 좋습니다.',work:'방문·미팅·연락 등 행동을 먼저 시작해보세요.',life:'가벼운 산책이나 외출이 기분 전환에 도움이 됩니다.'},
goat:{name:'양띠',icon:'🐑',summary:'협력이 좋은 결과로 이어질 수 있습니다.',money:'공동지출이나 가족예산은 기준을 명확히 하세요.',work:'도움을 요청하거나 역할을 나누면 효율이 높아집니다.',life:'주변 사람을 챙기는 작은 행동이 좋은 흐름을 만듭니다.'},
monkey:{name:'원숭이띠',icon:'🐵',summary:'아이디어보다 확인이 먼저입니다.',money:'좋아 보이는 조건도 세부 내용을 다시 확인하세요.',work:'새 아이디어는 실행 전 체크리스트를 만들어보세요.',life:'너무 많은 일을 동시에 벌이지 않는 것이 좋습니다.'},
rooster:{name:'닭띠',icon:'🐔',summary:'시간 관리가 중요한 날입니다.',money:'납부일과 결제일을 한 번 확인해보세요.',work:'중요 업무를 오전이나 집중되는 시간에 배치하세요.',life:'일정을 조금 비워두면 여유가 생깁니다.'},
dog:{name:'개띠',icon:'🐶',summary:'경험자의 조언이 도움이 되는 날입니다.',money:'혼자 판단하기 어려운 금융문제는 전문가와 상의해보세요.',work:'과거에 잘됐던 방식을 다시 활용해보세요.',life:'익숙한 사람과의 대화가 안정감을 줍니다.'},
pig:{name:'돼지띠',icon:'🐷',summary:'여유를 가지면 흐름이 더 좋아집니다.',money:'급하게 결정하기보다 하루 정도 생각해보세요.',work:'조급함을 줄이면 놓친 부분이 보일 수 있습니다.',life:'충분한 휴식과 식사 시간을 챙겨보세요.'}
};
const ORDER=[['rat','🐭 쥐띠'],['ox','🐮 소띠'],['tiger','🐯 호랑이띠'],['rabbit','🐰 토끼띠'],['dragon','🐲 용띠'],['snake','🐍 뱀띠'],['horse','🐴 말띠'],['goat','🐑 양띠'],['monkey','🐵 원숭이띠'],['rooster','🐔 닭띠'],['dog','🐶 개띠'],['pig','🐷 돼지띠']];
function addStyle(){const s=document.createElement('style');s.textContent='.fortune-picker{display:grid;grid-template-columns:220px 1fr;gap:14px;margin-top:14px}.fortune-picker select{width:100%;border:1px solid #dbe2ea;border-radius:12px;padding:12px;background:#fff;font-weight:800}.fortune-result{border:1px solid #eee7d8;border-radius:16px;background:#fffaf0;padding:18px}.fortune-result h3{margin:0 0 8px;font-size:21px}.fortune-summary{font-weight:800;line-height:1.6;margin-bottom:12px}.fortune-detail{display:grid;grid-template-columns:repeat(3,1fr);gap:9px}.fortune-detail div{background:#fff;border:1px solid #eee7d8;border-radius:12px;padding:12px;font-size:13px;line-height:1.55}.lotto-card{background:#fff;border:1px solid #e5e9ef;border-radius:18px;padding:18px}.lotto-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:10px;margin-top:12px}.lotto-item{background:#f7f9fc;border:1px solid #e3e8ef;border-radius:14px;padding:14px}.lotto-item b{display:block;margin-bottom:6px}.lotto-item strong{font-size:19px}.lotto-link{display:inline-block;margin-top:12px;text-decoration:none;border-radius:11px;padding:10px 14px;background:#245b9e;color:#fff;font-weight:800;font-size:13px}.lotto-note{font-size:11px;color:#778292;line-height:1.55;margin-top:10px}@media(max-width:700px){.fortune-picker{grid-template-columns:1fr}.fortune-detail,.lotto-grid{grid-template-columns:1fr}}';document.head.appendChild(s)}
function findFortune(){return Array.from(document.querySelectorAll('section')).find(sec=>{const h=sec.querySelector('h2');return h&&h.textContent.trim().startsWith('오늘의 운세')})}
function renderFortune(){const sec=findFortune();if(!sec)return;sec.classList.add('card');sec.innerHTML='<div style="display:flex;justify-content:space-between;gap:12px;align-items:center;flex-wrap:wrap"><div><h2 class="title" style="margin-bottom:4px">오늘의 운세</h2><div class="muted">띠를 선택하면 오늘의 운세를 볼 수 있습니다. 재미로 참고해주세요.</div></div></div><div class="fortune-picker"><div><select id="fponZodiac" aria-label="띠 선택"></select></div><div id="fponFortuneResult" class="fortune-result"></div></div>';
const sel=sec.querySelector('#fponZodiac'),out=sec.querySelector('#fponFortuneResult');ORDER.forEach(([v,t])=>{const o=document.createElement('option');o.value=v;o.textContent=t;sel.appendChild(o)});const saved=localStorage.getItem('fponZodiac')||'rat';if(FORTUNES[saved])sel.value=saved;function paint(){const f=FORTUNES[sel.value];out.innerHTML='<h3>'+f.icon+' '+f.name+'</h3><div class="fortune-summary">'+f.summary+'</div><div class="fortune-detail"><div><b>💰 금전</b><br>'+f.money+'</div><div><b>📌 일·활동</b><br>'+f.work+'</div><div><b>🌿 생활</b><br>'+f.life+'</div></div>';localStorage.setItem('fponZodiac',sel.value)}sel.onchange=paint;paint();return sec}
function renderLotto(after){if(!after)return;const sec=document.createElement('section');sec.className='sec lotto-card';sec.innerHTML='<div style="display:flex;justify-content:space-between;gap:12px;align-items:flex-start;flex-wrap:wrap"><div><h2 class="title" style="margin-bottom:4px">🎱 로또 6/45 정보</h2><div class="muted">이번 주 추첨·구매 기본정보를 간단히 확인합니다.</div></div><span class="date-badge">2026.08.28 기준</span></div><div class="lotto-grid"><div class="lotto-item"><b>이번 주 추첨</b><strong>8/29(토) 20:35경</strong></div><div class="lotto-item"><b>토요일 판매</b><strong>20:00까지</strong></div><div class="lotto-item"><b>1게임 가격</b><strong>1,000원</strong></div><div class="lotto-item"><b>1등 당첨확률</b><strong>1 / 8,145,060</strong></div></div><a class="lotto-link" href="https://www.dhlottery.co.kr/lt645/intro" target="_blank" rel="noopener">동행복권 공식 당첨정보 보기</a><div class="lotto-note">※ 로또 정보는 동행복권 공식 안내 기준입니다. 운세와 당첨 가능성은 관련이 없으며, FPON은 당첨번호 예측 기능을 제공하지 않습니다. 만 19세 미만은 복권을 구매할 수 없습니다.</div>';after.insertAdjacentElement('afterend',sec)}
addStyle();const f=renderFortune();renderLotto(f);
const insuranceScript=document.createElement('script');insuranceScript.src=(location.pathname.includes('/customer/')?'../':'')+'insurance-tools.js?v=20260829-2';document.head.appendChild(insuranceScript);
})();