(function(){
const LIFE=[
{name:'교보생명',tel:'1588-1001',claimTel:'1588-1810',url:'https://app.kyobo.com/dgt/web/dti/insurance/accInq/intro',methods:'홈페이지·모바일, FP 대리접수, 고객PLAZA/지점, 등기우편 등'},
{name:'한화생명',tel:'1588-6363',url:'https://www.hanwhalife.com/static/main/customerCenter/documents/CU_RD00000_T1T100.jsp',methods:'홈페이지·모바일앱, FP 대리청구, 방문, 등기우편, FAX·보이는 ARS 등'},
{name:'삼성생명',tel:'1588-3114',url:'https://www.samsunglife.com/',methods:'홈페이지·모바일, 고객센터·방문 등 공식 보험금 청구 안내에서 확인'},
{name:'KB라이프생명',tel:'1588-3374',url:'https://www.kblife.co.kr/customer-center/benefitClaimMethod.do',methods:'인터넷·모바일·전자신청, 라이프파트너, 고객플라자, 등기우편, FAX'},
{name:'신한라이프',tel:'1588-5580',url:'https://www.shinhanlife.co.kr/',methods:'홈페이지·모바일, 고객센터 등 공식 보험금 청구 안내에서 확인'},
{name:'미래에셋생명',tel:'1588-0220',url:'https://life.miraeasset.com/',methods:'홈페이지·모바일, 고객센터 등 공식 보험금 청구 안내에서 확인'},
{name:'DB생명',tel:'1588-3131',url:'https://www.idblife.com/',methods:'홈페이지·모바일, 고객센터 등 공식 보험금 청구 안내에서 확인'},
{name:'동양생명',tel:'1577-1004',url:'https://www.myangel.co.kr/',methods:'홈페이지·모바일, 고객센터 등 공식 보험금 청구 안내에서 확인'},
{name:'라이나생명',tel:'1588-0058',url:'https://www.lina.co.kr/',methods:'홈페이지·모바일, 고객센터 등 공식 보험금 청구 안내에서 확인'},
{name:'NH농협생명',tel:'1544-4000',url:'https://www.nhlife.co.kr/',methods:'홈페이지·모바일, 고객센터 등 공식 보험금 청구 안내에서 확인'}];
const NONLIFE=[
{name:'삼성화재',tel:'1588-5114',url:'https://www.samsungfire.com/vh/page/VH.HPCLA001.do',methods:'홈페이지·모바일에서 질병/상해 청구, 서류등록 후 심사·지급'},
{name:'KB손해보험',tel:'1544-0114',url:'https://www.kbinsure.co.kr/CG205010001.ec',methods:'PC·모바일, 우편, 방문, FAX, 계약관리 담당자 접수'},
{name:'DB손해보험',tel:'1588-0100',url:'https://www.idbins.com/',methods:'홈페이지·모바일, 고객센터 등 공식 보험금 청구 안내에서 확인'},
{name:'현대해상',tel:'1588-5656',url:'https://www.hi.co.kr/',methods:'홈페이지·모바일, 고객센터 등 공식 보험금 청구 안내에서 확인'},
{name:'메리츠화재',tel:'1566-7711',url:'https://www.meritzfire.com/',methods:'홈페이지·모바일, 고객센터 등 공식 보험금 청구 안내에서 확인'},
{name:'롯데손해보험',tel:'1588-3344',url:'https://www.lotteins.co.kr/',methods:'ALICE 앱·공식 홈페이지 및 고객센터 안내'},
{name:'흥국화재',tel:'1688-1688',url:'https://www.heungkukfire.co.kr/',methods:'홈페이지·모바일, 고객센터 등 공식 보험금 청구 안내에서 확인'},
{name:'한화손해보험',tel:'1566-8000',url:'https://www.hwgeneralins.com/',methods:'홈페이지·모바일, 고객센터 등 공식 보험금 청구 안내에서 확인'},
{name:'NH농협손해보험',tel:'1644-9000',url:'https://www.nhfire.co.kr/',methods:'홈페이지·모바일, 고객센터 등 공식 보험금 청구 안내에서 확인'},
{name:'AXA손해보험',tel:'1566-1566',url:'https://www.axa.co.kr/',methods:'공식 홈페이지 및 고객센터에서 사고·보험금 접수 방법 확인'},
{name:'AIG손해보험',tel:'1544-2792',url:'https://www.aig.co.kr/',methods:'공식 홈페이지 및 고객센터에서 보험금 청구 방법 확인'}];
const ALL=LIFE.concat(NONLIFE);
const MEALS=[
{name:'고등어구이 정식',desc:'등푸른생선 단백질과 채소 반찬을 함께 챙기는 균형 한 끼',set:'고등어구이 · 현미밥 반 공기~1공기 · 된장국 · 나물 2가지',tip:'국물은 적게, 생선과 채소부터 천천히 드세요.'},
{name:'닭가슴살 비빔밥',desc:'단백질과 채소를 한 그릇에 담아 오후까지 든든한 메뉴',set:'닭가슴살 · 잡곡밥 · 상추·오이·당근 · 달걀',tip:'고추장은 평소의 절반만 넣어도 충분합니다.'},
{name:'두부김치와 잡곡밥',desc:'부담은 줄이고 포만감은 살리는 따뜻한 집밥형 메뉴',set:'구운 두부 · 볶은 김치 · 잡곡밥 · 김 또는 샐러드',tip:'김치는 한 번 가볍게 씻거나 양을 줄이면 나트륨을 낮출 수 있습니다.'},
{name:'소고기 미역국 한상',desc:'속이 편하고 단백질을 함께 챙기기 좋은 한식 한 끼',set:'소고기 미역국 · 밥 · 두부부침 · 오이무침',tip:'국물보다 건더기를 충분히 드세요.'},
{name:'연어 샐러드볼',desc:'더운 날 가볍지만 영양 밀도는 높은 한 끼',set:'연어 · 잎채소 · 방울토마토 · 삶은 달걀 · 통곡물빵',tip:'드레싱은 따로 받아 찍어 먹으면 열량을 줄이기 쉽습니다.'},
{name:'제육볶음 쌈밥',desc:'외식 메뉴도 채소 비중을 높이면 균형 잡힌 한 끼가 됩니다.',set:'제육볶음 · 상추·깻잎 · 밥 · 된장 또는 마늘 소량',tip:'밥은 조금 줄이고 쌈 채소를 넉넉히 드세요.'},
{name:'순두부찌개와 계란말이',desc:'부드러운 단백질을 두 가지로 챙기는 따뜻한 메뉴',set:'순두부찌개 · 계란말이 · 밥 · 김치 소량',tip:'찌개 국물은 반만 드시고 두부 건더기를 충분히 챙기세요.'},
{name:'보리밥과 청국장',desc:'통곡물과 콩 단백질을 함께 챙기는 전통 한식',set:'보리밥 · 청국장 · 나물 · 계란 또는 두부',tip:'청국장은 건더기 위주로 먹고 짠 반찬은 한 가지로 줄이세요.'},
{name:'오징어볶음 덮밥',desc:'쫄깃한 해산물 단백질과 채소를 함께 먹는 활력 메뉴',set:'오징어볶음 · 양배추·양파 · 밥 · 미역냉국',tip:'덮밥 소스는 과하지 않게 하고 채소 양을 늘리세요.'},
{name:'돼지고기 수육 한상',desc:'튀기지 않은 조리법으로 단백질을 든든하게 챙기는 메뉴',set:'수육 · 상추·배추 · 밥 · 무생채',tip:'쌈장과 새우젓은 조금만 사용하세요.'},
{name:'메밀국수와 닭안심',desc:'입맛 없는 날 시원하게 먹기 좋은 가벼운 단백질 한 끼',set:'메밀국수 · 닭안심 · 오이 · 김가루',tip:'육수는 전부 마시지 않고 면과 건더기 중심으로 드세요.'},
{name:'콩나물밥과 구운 두부',desc:'재료는 단순하지만 섬유질과 단백질을 고루 챙기는 메뉴',set:'콩나물밥 · 구운 두부 · 양념간장 소량 · 김',tip:'양념장은 숟가락으로 붓기보다 조금씩 비벼 드세요.'},
{name:'불고기 채소쌈',desc:'익숙한 메뉴를 채소 중심으로 바꿔 먹는 실용적인 한 끼',set:'소불고기 · 모둠쌈 · 잡곡밥 · 버섯',tip:'불고기 양념은 적당히, 버섯과 채소를 함께 많이 드세요.'},
{name:'김치볶음밥과 달걀',desc:'간편식도 채소와 단백질을 더하면 한 끼 균형이 좋아집니다.',set:'김치볶음밥 · 달걀프라이 · 오이·토마토 · 김',tip:'햄은 줄이고 계란이나 두부를 추가하는 편이 좋습니다.'}
];
function css(){const s=document.createElement('style');s.textContent=`.claim-tool{margin-top:18px;background:#fff;border:1px solid #e3e9f0;border-radius:18px;padding:20px}.claim-tool h2{margin:0 0 8px;font-size:21px}.claim-grid{display:grid;grid-template-columns:1fr 1fr;gap:12px;margin-top:14px}.claim-box{border:1px solid #e5eaf0;border-radius:15px;padding:16px;background:#f9fbfd}.claim-box h3{margin:0 0 8px;font-size:16px}.claim-select{width:100%;border:1px solid #d9e1ea;border-radius:11px;padding:10px;background:#fff;font-weight:800}.claim-result{margin-top:12px;line-height:1.7;color:#4f5d6e;font-size:13px}.claim-result b{color:#24384d}.claim-actions{display:flex;gap:8px;flex-wrap:wrap;margin-top:12px}.claim-btn{border:0;border-radius:11px;padding:10px 13px;font-weight:900;cursor:pointer;text-decoration:none;display:inline-block}.claim-btn.primary{background:#245b9e;color:#fff}.claim-btn.light{background:#eef3f8;color:#35506f}.callcenter-tool{margin-top:18px;padding:18px;border-radius:18px;background:#f7f9fc;border:1px solid #e1e6ed}.callcenter-row{display:grid;grid-template-columns:180px 1fr auto;gap:10px;align-items:center;margin-top:10px}.call-number{font-size:20px;font-weight:900;color:#245b9e}.claim-note{font-size:11px;color:#7a8592;line-height:1.55;margin-top:10px}.fuel-tools{margin-top:12px;padding:12px;border-radius:14px;background:#f7fafc;border:1px solid #e2e8ef}.fuel-tools-title{display:flex;justify-content:space-between;gap:8px;align-items:center;margin-bottom:9px}.fuel-tools-title b{font-size:13px}.fuel-tools-title small{color:#718096}.fuel-controls{display:grid;grid-template-columns:minmax(130px,1fr) 110px auto;gap:8px}.fuel-select,.fuel-type{min-width:0;border:1px solid #dbe2ea;border-radius:10px;padding:9px 10px;background:#fff;font-weight:700;color:#34465a}.fuel-search-btn{border:0;border-radius:10px;padding:9px 12px;background:#245b9e;color:#fff;font-weight:900;cursor:pointer}.fuel-help{margin-top:8px;color:#718096;font-size:11px;line-height:1.5}.fuel-current{margin-top:8px;font-size:12px;font-weight:800;color:#315b86}.meal-card{background:linear-gradient(135deg,#fffdf6,#fff);border:1px solid #efe5c8;border-radius:18px;padding:20px}.meal-head{display:flex;justify-content:space-between;gap:12px;align-items:flex-start}.meal-date{font-size:12px;padding:6px 9px;border-radius:999px;background:#f8f1dd;color:#7c6431;font-weight:800}.meal-name{font-size:25px;font-weight:900;margin:12px 0 6px;color:#3d3525}.meal-desc{color:#6a6254;font-size:13px;line-height:1.65}.meal-grid{display:grid;grid-template-columns:1fr 1fr;gap:10px;margin-top:14px}.meal-mini{padding:13px;border-radius:13px;background:#fff;border:1px solid #eee7d8;font-size:13px;line-height:1.6}.meal-mini b{display:block;margin-bottom:4px;color:#594b2c}@media(max-width:650px){.claim-grid,.callcenter-row,.fuel-controls,.meal-grid{grid-template-columns:1fr}.claim-actions{display:grid}.claim-btn{text-align:center}.fuel-search-btn{width:100%}}`;document.head.appendChild(s)}
function optionHtml(){return '<optgroup label="생명보험">'+LIFE.map(x=>`<option value="${x.name}">${x.name}</option>`).join('')+'</optgroup><optgroup label="손해보험">'+NONLIFE.map(x=>`<option value="${x.name}">${x.name}</option>`).join('')+'</optgroup>'}
function byName(n){return ALL.find(x=>x.name===n)||ALL[0]}
function claimSection(customer){const sec=document.createElement('section');sec.className='claim-tool';sec.innerHTML=customer?`<h2>🧾 보험금 청구 도우미</h2><div style="color:#667385;font-size:13px;line-height:1.6">병원 진료·입원·수술 후 보험금 청구가 필요하다면 보험사를 선택해 공식 청구 안내를 확인하거나 담당 FP에게 의뢰·문의할 수 있습니다.</div><div class="claim-grid"><div class="claim-box"><h3>보험사 선택</h3><select class="claim-select claim-insurer">${optionHtml()}</select><div class="claim-result"></div></div><div class="claim-box"><h3>FP에게 청구 의뢰 / 문의</h3><div class="claim-result">진료일, 병원명, 치료내용과 보유한 진료비 영수증·세부내역서 등을 준비해 담당 FP에게 문의해주세요. 필요한 서류는 청구 사유와 보험사에 따라 달라질 수 있습니다.</div><div class="claim-actions"><button class="claim-btn primary ask-fp">담당 FP에게 문의하기</button></div></div></div>`:`<h2>🧾 보험금 청구</h2><div style="color:#667385;font-size:13px;line-height:1.6">보험사를 선택하면 해당 회사의 대표적인 접수 채널과 공식 보험금 청구 안내 페이지를 바로 확인할 수 있습니다.</div><div class="claim-grid"><div class="claim-box"><h3>보험사별 청구 방법</h3><select class="claim-select claim-insurer">${optionHtml()}</select><div class="claim-result"></div></div><div class="claim-box"><h3>FP 체크 포인트</h3><div class="claim-result"><b>① 청구사유 확인</b> 입원·수술·진단·통원·실손 여부<br><b>② 서류 확인</b> 청구서, 진료비 영수증, 세부내역서, 진단서 등<br><b>③ 접수채널 선택</b> 앱·웹·FP대리접수·FAX·우편·방문 중 보험사 기준 확인<br><b>④ 진행관리</b> 접수일·보완요청·지급일을 고객 터치 이력과 연결</div></div></div>`;return sec}
function bindClaim(sec,customer){const sel=sec.querySelector('.claim-insurer'),out=sec.querySelector('.claim-result');function draw(){const x=byName(sel.value);out.innerHTML=`<b>${x.name}</b><br>${x.methods}<br>대표 콜센터 <b>${x.tel}</b>${x.claimTel?` · 사고보험금 ${x.claimTel}`:''}<div class="claim-actions"><a class="claim-btn primary" href="${x.url}" target="_blank" rel="noopener">공식 청구 안내</a><a class="claim-btn light" href="tel:${x.claimTel||x.tel}">전화하기</a></div>`}sel.onchange=draw;draw();if(customer){const b=sec.querySelector('.ask-fp');if(b)b.onclick=()=>{const target=[...document.querySelectorAll('section')].find(x=>/궁금한 점|연락|문의/.test(x.textContent));if(target)target.scrollIntoView({behavior:'smooth',block:'center'});else alert('담당 FP 연락처가 등록되면 바로 연결됩니다.')}}}
function callCenter(){const sec=document.createElement('section');sec.className='callcenter-tool';sec.innerHTML=`<h2 style="margin:0;font-size:20px">☎️ 보험사 콜센터 찾기</h2><div style="color:#667385;font-size:13px;margin-top:6px">보험사를 선택하면 대표 콜센터 번호와 공식 홈페이지를 확인할 수 있습니다.</div><div class="callcenter-row"><select class="claim-select cc-select">${optionHtml()}</select><div><div class="cc-name" style="font-weight:900"></div><div class="call-number cc-number"></div></div><div class="claim-actions"><a class="claim-btn primary cc-call">전화하기</a><a class="claim-btn light cc-web" target="_blank" rel="noopener">공식 홈페이지</a></div></div><div class="claim-note">※ 콜센터 번호·접수방법은 보험사 운영정책에 따라 변경될 수 있으므로 중요한 청구 전에는 각 보험사 공식 홈페이지에서 최종 확인해주세요.</div>`;const sel=sec.querySelector('.cc-select');function draw(){const x=byName(sel.value);sec.querySelector('.cc-name').textContent=x.name;sec.querySelector('.cc-number').textContent=x.tel+(x.claimTel?' · 사고보험금 '+x.claimTel:'');sec.querySelector('.cc-call').href='tel:'+(x.claimTel||x.tel);sec.querySelector('.cc-web').href=x.url}sel.onchange=draw;draw();return sec}
function addFuelTools(){const fuel=document.querySelector('.ec.fuel');if(!fuel||fuel.querySelector('.fuel-tools'))return;const regions=['서울','부산','대구','인천','광주','대전','울산','세종','경기','강원','충북','충남','전북','전남','경북','경남','제주'];const box=document.createElement('div');box.className='fuel-tools';box.innerHTML=`<div class="fuel-tools-title"><b>⛽ 기름값 정보 · 지역별 최저가 찾기</b><small>오피넷 연결</small></div><div class="fuel-controls"><select id="fuelRegion" class="fuel-select">${regions.map(x=>`<option value="${x}">${x}</option>`).join('')}</select><select id="fuelType" class="fuel-type"><option value="gasoline">휘발유</option><option value="diesel">경유</option></select><button class="fuel-search-btn" type="button" id="fuelSearchBtn">최저가 주유소 찾기</button></div><div class="fuel-current" id="fuelCurrent">서울 기준 · 유가 카드의 전국 평균과 함께 비교해보세요.</div><div class="fuel-help">버튼을 누르면 오피넷의 지역별 싼 주유소 검색으로 이동합니다. 실제 판매가는 주유소별·시간대별로 달라질 수 있으니 방문 전 최종 가격을 확인하세요.</div>`;fuel.appendChild(box);const r=box.querySelector('#fuelRegion'),t=box.querySelector('#fuelType'),cur=box.querySelector('#fuelCurrent');const weather=document.getElementById('weatherRegion');if(weather&&weather.options.length){const txt=weather.options[weather.selectedIndex]?.text||'';const match=regions.find(x=>txt.includes(x));if(match)r.value=match}function draw(){cur.textContent=`${r.value} · ${t.options[t.selectedIndex].text} 최저가 주유소 확인`}r.onchange=draw;t.onchange=draw;draw();box.querySelector('#fuelSearchBtn').onclick=()=>window.open('https://www.opinet.co.kr/searRgSelect.do','_blank','noopener')}
function addMeal(){if(location.pathname.includes('/customer/'))return;const anchor=[...document.querySelectorAll('section')].find(x=>/오늘의 운세/.test(x.textContent));if(!anchor||document.querySelector('.meal-card'))return;const now=new Date();const day=Math.floor(Date.UTC(now.getFullYear(),now.getMonth(),now.getDate())/86400000);const m=MEALS[day%MEALS.length];const sec=document.createElement('section');sec.className='sec meal-card';const date=`${now.getFullYear()}.${String(now.getMonth()+1).padStart(2,'0')}.${String(now.getDate()).padStart(2,'0')}`;sec.innerHTML=`<div class="meal-head"><div><h2 class="title" style="margin:0">오늘의 한끼식사 🍚</h2><div class="meal-desc">매일 다른 메뉴로 가볍게 참고하는 균형 한 끼 제안</div></div><span class="meal-date">${date}</span></div><div class="meal-name">${m.name}</div><div class="meal-desc">${m.desc}</div><div class="meal-grid"><div class="meal-mini"><b>오늘의 구성</b>${m.set}</div><div class="meal-mini"><b>한 끼 TIP</b>${m.tip}</div></div>`;anchor.parentNode.insertBefore(sec,anchor)}
function init(){css();addFuelTools();addMeal();const customer=location.pathname.includes('/customer/');const anchor=[...document.querySelectorAll('section')].find(x=>/오늘의 운세/.test(x.textContent));const claim=claimSection(customer);if(anchor&&anchor.parentNode){anchor.parentNode.insertBefore(claim,anchor);bindClaim(claim,customer)}else{const main=document.querySelector('.w')||document.body;main.appendChild(claim);bindClaim(claim,customer)}const footer=document.querySelector('footer,.footer');const cc=callCenter();if(footer&&footer.parentNode)footer.parentNode.insertBefore(cc,footer);else(document.querySelector('.w')||document.body).appendChild(cc)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();