(function(){
if(window.__fponInsuranceToolsLoaded)return;window.__fponInsuranceToolsLoaded=true;
const LIFE=[
{name:'교보생명',tel:'1588-1001',claimTel:'1588-1810',url:'https://app.kyobo.com/dgt/web/dti/insurance/accInq/intro',methods:'홈페이지·모바일, FP 대리접수, 고객PLAZA/지점, 등기우편 등'},
{name:'한화생명',tel:'1588-6363',url:'https://www.hanwhalife.com/',methods:'홈페이지·모바일앱, FP 대리청구, 방문, 등기우편, FAX 등'},
{name:'삼성생명',tel:'1588-3114',url:'https://www.samsunglife.com/',methods:'홈페이지·모바일, 고객센터·방문 등 공식 보험금 청구 안내에서 확인'},
{name:'KB라이프생명',tel:'1588-3374',url:'https://www.kblife.co.kr/',methods:'인터넷·모바일, 라이프파트너, 고객플라자, 등기우편, FAX'},
{name:'신한라이프',tel:'1588-5580',url:'https://www.shinhanlife.co.kr/',methods:'홈페이지·모바일, 고객센터 등 공식 안내에서 확인'}];
const NONLIFE=[
{name:'삼성화재',tel:'1588-5114',url:'https://www.samsungfire.com/',methods:'홈페이지·모바일에서 질병/상해 청구, 서류등록 후 심사·지급'},
{name:'KB손해보험',tel:'1544-0114',url:'https://www.kbinsure.co.kr/',methods:'PC·모바일, 우편, 방문, FAX, 계약관리 담당자 접수'},
{name:'DB손해보험',tel:'1588-0100',url:'https://www.idbins.com/',methods:'홈페이지·모바일, 고객센터 등 공식 안내에서 확인'},
{name:'현대해상',tel:'1588-5656',url:'https://www.hi.co.kr/',methods:'홈페이지·모바일, 고객센터 등 공식 안내에서 확인'},
{name:'메리츠화재',tel:'1566-7711',url:'https://www.meritzfire.com/',methods:'홈페이지·모바일, 고객센터 등 공식 안내에서 확인'}];
const ALL=LIFE.concat(NONLIFE);
const HEALTH_MEALS={0:{name:'닭안심 메밀국수 + 토마토 샐러드',desc:'주말 마무리는 포화지방 부담을 줄이고 채소와 단백질을 가볍게 챙기는 식사로 구성합니다.',set:'메밀국수 · 닭안심 · 토마토 · 오이 · 잎채소',tip:'육수는 모두 마시지 말고 토마토와 채소를 충분히 드세요.'},1:{name:'현미밥 + 고등어구이 + 브로콜리 + 두부',desc:'혈관 건강을 생각해 등푸른생선과 통곡물, 채소를 함께 챙기는 월요일 메뉴입니다.',set:'현미밥 · 고등어구이 · 브로콜리 · 두부 · 토마토',tip:'생선은 튀김보다 구이로, 국물과 짠 반찬은 줄여보세요.'},2:{name:'보리밥 + 두부버섯볶음 + 시금치나물',desc:'식물성 단백질과 식이섬유를 중심으로 부담 없이 챙기는 화요일 건강식입니다.',set:'보리밥 · 두부 · 버섯 · 시금치 · 오이무침',tip:'양념 간장은 적게 사용하고 채소의 양을 충분히 늘려보세요.'},3:{name:'연어구이 + 단호박 + 브로콜리 샐러드',desc:'생선과 채소를 중심으로 오메가3와 다양한 색의 채소를 챙기는 수요일 메뉴입니다.',set:'연어구이 · 단호박 · 브로콜리 · 방울토마토 · 잎채소',tip:'드레싱은 따로 두고 소량만 사용하면 좋습니다.'},4:{name:'닭가슴살 비빔밥 + 계란 + 나물',desc:'여러 채소와 담백한 단백질을 한 그릇에 담아 균형을 맞춘 목요일 건강식입니다.',set:'잡곡밥 · 닭가슴살 · 달걀 · 상추 · 당근 · 콩나물',tip:'고추장과 참기름은 평소보다 조금 줄이고 채소를 넉넉히 넣으세요.'},5:{name:'콩나물밥 + 구운 두부 + 김 + 토마토',desc:'콩과 채소 중심의 담백한 식사로 한 주의 외식 부담을 낮추는 금요일 건강식입니다.',set:'콩나물밥 · 구운 두부 · 김 · 토마토 · 오이',tip:'양념장은 밥에 붓기보다 조금씩 비벼 나트륨을 조절하세요.'},6:{name:'소고기 채소샤브샤브 + 소량의 잡곡밥',desc:'채소를 충분히 먹으면서 단백질도 챙길 수 있는 토요일 건강식입니다.',set:'소고기 · 배추 · 청경채 · 버섯 · 두부 · 잡곡밥 소량',tip:'국물은 적게 먹고 채소와 건더기 중심으로 드세요.'}};
function css(){if(document.getElementById('fpon-extra-css'))return;const s=document.createElement('style');s.id='fpon-extra-css';s.textContent='.claim-tool{margin-top:18px;background:#fff;border:1px solid #e3e9f0;border-radius:18px;padding:20px}.claim-grid{display:grid;grid-template-columns:1fr 1fr;gap:12px;margin-top:14px}.claim-box{border:1px solid #e5eaf0;border-radius:15px;padding:16px;background:#f9fbfd}.claim-select{width:100%;border:1px solid #d9e1ea;border-radius:11px;padding:10px;background:#fff;font-weight:800}.claim-result{margin-top:12px;line-height:1.7;color:#4f5d6e;font-size:13px}.claim-actions{display:flex;gap:8px;flex-wrap:wrap;margin-top:12px}.claim-btn{border:0;border-radius:11px;padding:10px 13px;font-weight:900;text-decoration:none;display:inline-block}.claim-btn.primary{background:#245b9e;color:#fff}.claim-btn.light{background:#eef3f8;color:#35506f}.callcenter-tool{margin-top:18px;padding:18px;border-radius:18px;background:#f7f9fc;border:1px solid #e1e6ed}.callcenter-row{display:grid;grid-template-columns:180px 1fr auto;gap:10px;align-items:center;margin-top:10px}.call-number{font-size:20px;font-weight:900;color:#245b9e}.health-meal{background:linear-gradient(135deg,#f6fff9,#fff);border:1px solid #dbeade;border-radius:18px;padding:20px}.health-name{font-size:24px;font-weight:900;margin:12px 0 6px;color:#244f36}.health-desc{color:#586a5f;font-size:13px;line-height:1.65}.health-grid{display:grid;grid-template-columns:1fr 1fr;gap:10px;margin-top:14px}.health-mini{padding:13px;border-radius:13px;background:#fff;border:1px solid #dfeae2;font-size:13px;line-height:1.6}@media(max-width:650px){.claim-grid,.callcenter-row,.health-grid{grid-template-columns:1fr}}';document.head.appendChild(s)}
function optionHtml(){return '<optgroup label="생명보험">'+LIFE.map(x=>'<option>'+x.name+'</option>').join('')+'</optgroup><optgroup label="손해보험">'+NONLIFE.map(x=>'<option>'+x.name+'</option>').join('')+'</optgroup>'}
function byName(n){return ALL.find(x=>x.name===n)||ALL[0]}
function bindSelect(sec){const sel=sec.querySelector('.claim-insurer'),out=sec.querySelector('.claim-result');function draw(){const x=byName(sel.value);out.innerHTML='<b>'+x.name+'</b><br>'+x.methods+'<br>대표 콜센터 <b>'+x.tel+'</b>'+(x.claimTel?' · 사고보험금 '+x.claimTel:'')+'<div class="claim-actions"><a class="claim-btn primary" href="'+x.url+'" target="_blank" rel="noopener">공식 청구 안내</a><a class="claim-btn light" href="tel:'+(x.claimTel||x.tel)+'">전화하기</a></div>'}sel.onchange=draw;draw()}
function findFortune(){return [...document.querySelectorAll('section')].find(x=>/오늘의 운세/.test(x.textContent))}
function placeLifestyle(){const fortune=findFortune();if(!fortune)return;const parent=fortune.parentNode;const news=[...document.querySelectorAll('section')].find(x=>/오늘의 뉴스/.test(x.textContent));if(news&&news.parentNode===parent)parent.insertBefore(fortune,news.nextSibling);let anchor=fortune;const lotto=document.querySelector('.lotto-card');if(lotto){parent.insertBefore(lotto,anchor.nextSibling);anchor=lotto}const health=document.querySelector('.health-meal');if(health){parent.insertBefore(health,anchor.nextSibling);anchor=health}}
function addHealthMeal(){if(document.querySelector('.health-meal'))return;const fortune=findFortune();if(!fortune)return;const now=new Date(),m=HEALTH_MEALS[now.getDay()],sec=document.createElement('section');sec.className='sec health-meal';sec.innerHTML='<h2 class="title" style="margin:0">오늘의 건강식 🥗</h2><div class="health-name">'+m.name+'</div><div class="health-desc">'+m.desc+'</div><div class="health-grid"><div class="health-mini"><b>오늘의 구성</b><br>'+m.set+'</div><div class="health-mini"><b>건강식 TIP</b><br>'+m.tip+'</div></div>';const lotto=document.querySelector('.lotto-card');(lotto||fortune).insertAdjacentElement('afterend',sec)}
function addSingleClaim(){document.querySelectorAll('.claim-tool').forEach(x=>x.remove());const customer=location.pathname.includes('/customer/'),sec=document.createElement('section');sec.className='claim-tool';sec.innerHTML=customer?'<h2>🧾 보험금 청구 도우미</h2><div class="claim-result">보험사를 선택해 공식 청구 안내를 확인하거나 담당 FP에게 문의할 수 있습니다.</div><div class="claim-grid"><div class="claim-box"><h3>보험사 선택</h3><select class="claim-select claim-insurer">'+optionHtml()+'</select><div class="claim-result"></div></div><div class="claim-box"><h3>청구 전 확인</h3><div class="claim-result">진료일·병원명·치료내용과 진료비 영수증·세부내역서 등 보유 서류를 먼저 확인해주세요.</div></div></div>':'<h2>🧾 보험금 청구</h2><div class="claim-result">보험사를 선택하면 대표 접수 채널과 공식 보험금 청구 안내를 확인할 수 있습니다.</div><div class="claim-grid"><div class="claim-box"><h3>보험사별 청구 방법</h3><select class="claim-select claim-insurer">'+optionHtml()+'</select><div class="claim-result"></div></div><div class="claim-box"><h3>FP 체크 포인트</h3><div class="claim-result">① 청구사유 · ② 서류 · ③ 접수채널 · ④ 진행관리</div></div></div>';const anchor=document.querySelector('.health-meal')||document.querySelector('.lotto-card')||findFortune();if(anchor)anchor.insertAdjacentElement('afterend',sec);else document.body.appendChild(sec);bindSelect(sec)}
function addCallCenter(){document.querySelectorAll('.callcenter-tool').forEach(x=>x.remove());const sec=document.createElement('section');sec.className='callcenter-tool';sec.innerHTML='<h2 style="margin:0;font-size:20px">☎️ 보험사 콜센터 찾기</h2><div class="callcenter-row"><select class="claim-select cc-select">'+optionHtml()+'</select><div><div class="cc-name" style="font-weight:900"></div><div class="call-number cc-number"></div></div><div class="claim-actions"><a class="claim-btn primary cc-call">전화하기</a><a class="claim-btn light cc-web" target="_blank" rel="noopener">공식 홈페이지</a></div></div>';const sel=sec.querySelector('.cc-select');function draw(){const x=byName(sel.value);sec.querySelector('.cc-name').textContent=x.name;sec.querySelector('.cc-number').textContent=x.tel;sec.querySelector('.cc-call').href='tel:'+(x.claimTel||x.tel);sec.querySelector('.cc-web').href=x.url}sel.onchange=draw;draw();const claim=document.querySelector('.claim-tool');if(claim)claim.insertAdjacentElement('afterend',sec);else document.body.appendChild(sec)}
function init(){css();addHealthMeal();placeLifestyle();addSingleClaim();addCallCenter()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();