(function(){
if(window.__fponInsuranceToolsLoaded)return;window.__fponInsuranceToolsLoaded=true;
const LIFE=[{name:'교보생명',tel:'1588-1001',claimTel:'1588-1810',url:'https://app.kyobo.com/dgt/web/dti/insurance/accInq/intro',methods:'홈페이지·모바일, FP 대리접수, 고객PLAZA/지점, 등기우편 등'},{name:'한화생명',tel:'1588-6363',url:'https://www.hanwhalife.com/',methods:'홈페이지·모바일앱, FP 대리청구, 방문, 등기우편, FAX 등'},{name:'삼성생명',tel:'1588-3114',url:'https://www.samsunglife.com/',methods:'홈페이지·모바일, 고객센터·방문 등 공식 보험금 청구 안내에서 확인'},{name:'KB라이프생명',tel:'1588-3374',url:'https://www.kblife.co.kr/',methods:'인터넷·모바일, 라이프파트너, 고객플라자, 등기우편, FAX'},{name:'신한라이프',tel:'1588-5580',url:'https://www.shinhanlife.co.kr/',methods:'홈페이지·모바일, 고객센터 등 공식 안내에서 확인'}];
const NONLIFE=[{name:'삼성화재',tel:'1588-5114',url:'https://www.samsungfire.com/',methods:'홈페이지·모바일에서 질병/상해 청구, 서류등록 후 심사·지급'},{name:'KB손해보험',tel:'1544-0114',url:'https://www.kbinsure.co.kr/',methods:'PC·모바일, 우편, 방문, FAX, 계약관리 담당자 접수'},{name:'DB손해보험',tel:'1588-0100',url:'https://www.idbins.com/',methods:'홈페이지·모바일, 고객센터 등 공식 안내에서 확인'},{name:'현대해상',tel:'1588-5656',url:'https://www.hi.co.kr/',methods:'홈페이지·모바일, 고객센터 등 공식 안내에서 확인'},{name:'메리츠화재',tel:'1566-7711',url:'https://www.meritzfire.com/',methods:'홈페이지·모바일, 고객센터 등 공식 안내에서 확인'}];const ALL=LIFE.concat(NONLIFE);
function isCustomer(){try{return window.parent!==window&&window.parent.location.pathname.includes('/customer/')}catch(e){return false}}
function css(){if(document.getElementById('fpon-extra-css'))return;const s=document.createElement('style');s.id='fpon-extra-css';s.textContent='.claim-tool,.callcenter-tool{margin-top:18px;background:#fff;border:1px solid #e3e9f0;border-radius:18px;padding:20px}.claim-grid{display:grid;grid-template-columns:1fr 1fr;gap:12px;margin-top:14px}.claim-box{border:1px solid #e5eaf0;border-radius:15px;padding:16px;background:#f9fbfd}.claim-select{width:100%;border:1px solid #d9e1ea;border-radius:11px;padding:10px;background:#fff;font-weight:800}.claim-result{margin-top:12px;line-height:1.7;color:#4f5d6e;font-size:13px}.claim-actions{display:flex;gap:8px;flex-wrap:wrap;margin-top:12px}.claim-btn{border:0;border-radius:11px;padding:10px 13px;font-weight:900;text-decoration:none;display:inline-block}.claim-btn.primary{background:#245b9e;color:#fff}.claim-btn.light{background:#eef3f8;color:#35506f}.callcenter-row{display:grid;grid-template-columns:180px 1fr auto;gap:10px;align-items:center;margin-top:10px}.call-number{font-size:20px;font-weight:900;color:#245b9e}.news4{grid-template-columns:repeat(3,1fr)!important}.news4 .news{min-height:150px}.news-kicker{display:inline-block;font-size:11px;font-weight:900;color:#245b9e;background:#eef5ff;border-radius:999px;padding:4px 8px;margin-bottom:8px}.news4 .news span{display:block}.news4 .news small{display:block;margin-top:10px;color:#7a8796;line-height:1.45}@media(max-width:800px){.news4{grid-template-columns:1fr!important}.claim-grid,.callcenter-row{grid-template-columns:1fr}}';document.head.appendChild(s)}
function optionHtml(){return '<optgroup label="생명보험">'+LIFE.map(x=>'<option>'+x.name+'</option>').join('')+'</optgroup><optgroup label="손해보험">'+NONLIFE.map(x=>'<option>'+x.name+'</option>').join('')+'</optgroup>'}function byName(n){return ALL.find(x=>x.name===n)||ALL[0]}
function enrichNews(){let sec=[...document.querySelectorAll('section')].find(x=>{const h=x.querySelector('h2');return h&&h.textContent.includes('오늘의 뉴스')});if(!sec){sec=document.createElement('section');sec.className='sec card';sec.innerHTML='<h2 class="title">오늘의 뉴스</h2><div class="news4"></div>';const market=document.querySelector('.market');if(market)market.insertAdjacentElement('afterend',sec);else(document.querySelector('.w')||document.body).appendChild(sec)}let grid=sec.querySelector('.news4');if(!grid){grid=document.createElement('div');grid.className='news4';sec.appendChild(grid)}const customer=isCustomer();const items=customer?[
['생활경제','9월 상반기 근로장려금 신청 시작','근로소득만 있는 대상 가구는 오늘부터 9월 15일까지 2026년 상반기분 근로장려금을 신청할 수 있습니다. 대상 여부는 홈택스·손택스 등에서 확인할 수 있습니다.','내가 대상인지 한 번 확인해두세요.'],
['증시','미국 증시 혼조·반도체주는 상대적 강세','8월 31일 뉴욕증시는 다우와 S&P500이 하락한 반면 필라델피아 반도체지수는 상승했습니다. 시장 전체보다 업종별 흐름 차이가 컸습니다.','하루의 지수보다 내 자산의 분산 상태가 더 중요합니다.'],
['물가·유가','국제유가 상승, 생활물가 영향 주의','중동의 군사적 긴장 재확대로 국제유가가 상승했습니다. 국제유가 움직임은 시차를 두고 국내 기름값과 생활물가에 영향을 줄 수 있습니다.','주유비·교통비 등 변동지출을 체크해보세요.'],
['생활','전국 휘발유 약 1,860원·경유 1,844원/L','9월 1일 공개된 오피넷 기반 전국 평균 가격은 휘발유 약 1,860원, 경유 약 1,844원/L 수준입니다. 지역과 주유소에 따라 실제 가격은 다릅니다.','주유 전 주변 가격 비교가 도움이 됩니다.'],
['정책','정기국회 100일 일정 시작','오늘 제22대 국회 후반기 첫 정기국회가 시작됩니다. 9월 인사청문, 10월 국정감사, 11월 예산안 심사가 주요 일정입니다.','세금·복지·부동산 관련 제도 변화도 함께 지켜볼 필요가 있습니다.'],
['건강·재무','9월 첫날, 고정지출을 점검하세요','보험료·통신비·카드결제·구독료처럼 매달 반복되는 지출을 한 번에 확인하면 가계 현금흐름을 파악하기 쉬워집니다.','이번 달 한 가지 불필요한 지출만 찾아보세요.']
]:[
['시장','미국 증시 혼조·반도체 상대적 강세','8월 31일 다우 -0.70%, S&P500 -0.33%, 나스닥 종합 -0.12%로 약세였지만 나스닥100과 필라델피아 반도체지수는 상승했습니다.','변액 상담 시 지수 전체보다 펀드별 편입자산과 업종 노출을 함께 확인하세요.'],
['금리·유가','중동 긴장 재확대, 유가·채권금리 상승','미국과 이란의 군사적 긴장이 다시 커지며 브렌트유와 WTI가 상승했고 미국 국채금리도 올랐습니다. 인플레이션과 금리 경로가 다시 시장 변수로 부각됐습니다.','해외주식·채권·원자재 관련 고객의 변동성 설명에 활용할 이슈입니다.'],
['정책','정기국회 오늘 개막','제22대 국회 후반기 첫 정기국회가 오늘부터 100일간 진행됩니다. 9월 청문, 10월 국감, 11월 2027년도 예산안 심사가 예정돼 있습니다.','세제·부동산·금융 관련 입법 이슈를 고객 상담 전에 점검하세요.'],
['세무','2026 상반기 근로장려금 신청 시작','근로소득만 있는 대상 가구의 상반기분 근로장려금 신청 기간이 9월 1일부터 15일까지입니다.','대상 고객에게 생활밀착형 안내 소재로 활용할 수 있습니다.'],
['생활물가','전국 휘발유 약 1,860원/L','9월 1일 공개된 오피넷 기반 전국 평균은 휘발유 약 1,860원, 경유 약 1,844원/L 수준입니다. 국제유가 상승이 향후 국내 가격에 미칠 영향도 관찰할 필요가 있습니다.','고객용 생활금융 브리핑에서 체감물가 지표로 활용하세요.'],
['FP 체크','월초 보험금 청구·고정지출 점검','9월 첫 영업일에는 미청구 보험금, 보완서류, 지급 진행건과 함께 고객의 보험료·대출이자·자동이체 변화를 점검하기 좋습니다.','오늘 우선순위: 보험금 미결 건 → 납입 이슈 → 상담 후속 연락.']
];grid.innerHTML=items.map(x=>'<div class="news"><span class="news-kicker">'+x[0]+'</span><b>'+x[1]+'</b><span>'+x[2]+'</span><small>✓ '+x[3]+'</small></div>').join('')}
function bindSelect(sec){const sel=sec.querySelector('.claim-insurer'),out=sec.querySelector('.claim-result');function draw(){const x=byName(sel.value);out.innerHTML='<b>'+x.name+'</b><br>'+x.methods+'<br>대표 콜센터 <b>'+x.tel+'</b><div class="claim-actions"><a class="claim-btn primary" href="'+x.url+'" target="_blank" rel="noopener">공식 청구 안내</a><a class="claim-btn light" href="tel:'+(x.claimTel||x.tel)+'">전화하기</a></div>'}sel.onchange=draw;draw()}
function findFortune(){return [...document.querySelectorAll('section')].find(x=>/오늘의 운세/.test(x.textContent))}function placeLifestyle(){const f=findFortune(),news=[...document.querySelectorAll('section')].find(x=>/오늘의 뉴스/.test(x.textContent));if(f&&news&&f.parentNode===news.parentNode)f.parentNode.insertBefore(f,news.nextSibling)}
function addSingleClaim(){document.querySelectorAll('.claim-tool').forEach(x=>x.remove());const customer=isCustomer(),sec=document.createElement('section');sec.className='claim-tool';sec.innerHTML=customer?'<h2>🧾 보험금 청구 도우미</h2><div class="claim-result">보험사를 선택해 공식 청구 안내를 확인하거나 담당 FP에게 문의할 수 있습니다.</div><div class="claim-grid"><div class="claim-box"><h3>보험사 선택</h3><select class="claim-select claim-insurer">'+optionHtml()+'</select><div class="claim-result"></div></div><div class="claim-box"><h3>청구 전 확인</h3><div class="claim-result">진료일·병원명·치료내용과 영수증·세부내역서 등 보유 서류를 먼저 확인해주세요.</div></div></div>':'<h2>🧾 보험금 청구</h2><div class="claim-result">보험사를 선택하면 대표 접수 채널과 공식 보험금 청구 안내를 확인할 수 있습니다.</div><div class="claim-grid"><div class="claim-box"><h3>보험사별 청구 방법</h3><select class="claim-select claim-insurer">'+optionHtml()+'</select><div class="claim-result"></div></div><div class="claim-box"><h3>FP 체크 포인트</h3><div class="claim-result">① 청구사유 · ② 서류 · ③ 접수채널 · ④ 진행관리</div></div></div>';const anchor=document.querySelector('.health-meal')||document.querySelector('.lotto-card')||findFortune();if(anchor)anchor.insertAdjacentElement('afterend',sec);else document.body.appendChild(sec);bindSelect(sec)}
function addCallCenter(){document.querySelectorAll('.callcenter-tool').forEach(x=>x.remove());const sec=document.createElement('section');sec.className='callcenter-tool';sec.innerHTML='<h2 style="margin:0;font-size:20px">☎️ 보험사 콜센터 찾기</h2><div class="callcenter-row"><select class="claim-select cc-select">'+optionHtml()+'</select><div><div class="cc-name" style="font-weight:900"></div><div class="call-number cc-number"></div></div></div>';const sel=sec.querySelector('.cc-select');function draw(){const x=byName(sel.value);sec.querySelector('.cc-name').textContent=x.name;sec.querySelector('.cc-number').textContent=x.tel}sel.onchange=draw;draw();const claim=document.querySelector('.claim-tool');if(claim)claim.insertAdjacentElement('afterend',sec)}
function init(){css();enrichNews();placeLifestyle();addSingleClaim();addCallCenter()}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();